site_name: envas（エンバス） お知らせサイト
site_description: WEB 席次表 envas（エンバス） お知らせサイトです。
site_author: envas
site_url: https://info.envas.jp/
copyright: "&copy; 2025 WISH LLC. All rights reserved."

theme:
  name: material
  logo: images/envas.png
  favicon: images/favicon.ico
  language: ja
  palette:
    scheme: default
    primary: custom
  features:
    - navigation.top
  icon:
    admonition:
      note: octicons/tag-16

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: "ja"
  - rss:
      match_path: ".*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
      categories:
        - tags
      feeds_filenames:
        rss_created: feed.xml
      json_feed_enabled: false

extra:
  generator: false
  social:
    - icon: fontawesome/solid/rss
      link: /feed.xml
      name: RSS フィード

nav:
  - ホーム: index.md
  - お知らせ:
    - news/2026-07-16-collaborative-editing.md
    - news/2026-06-23-seating-chart-image.md
    - news/2026-05-04-guest-csv-import.md
    - news/2026-04-13-transaction-history.md
    - news/2026-04-01-photo-gallery.md
    - news/2026-03-27-add-after-party.md
    - news/2026-03-24-add-guest-and-maintenance.md
    - news/2026-02-14-add-applepay-and-paypay.md
    - news/2026-01-19-policy-pages.md
  - RSS: /feed.xml

markdown_extensions:
  - nl2br
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
